services:
  - type: web
    name: flash-francais-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    preDeployCommand: cp .env.production .env && python init_db.py
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash-francais-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: RENDER
        value: true

databases:
  - name: flash-francais-db
    databaseName: flashfrdb
    plan: free
