del
tests\test_enhanced_session_generation.py
del
tests\test_enum_fix.py
del
tests\test_final_integration.py
del
tests\test_fix_verification.py
del
tests\test_html_editor_integration.py
del
tests\test_html_editor_prompt.py
del
tests\test_introsequence_implementation.py
del
tests\test_list_user_resources.py
del
tests\test_logging_fix.py
del
tests\test_oeuvre_association_fix.py
del
tests\test_oeuvre_ids_in_prompt.py
del
tests\test_qcm_integration.py
del
tests\test_resource_content_integration.py
del
tests\test_resource_content.py
del
tests\test_session_creation_with_oeuvres.py
del
tests\test_session_generation.py
del
tests\test_session_oeuvres.py
del
tests\test_simplified_session_generation.py
del
tests\test_study_objects.py
del
tests\test_textereconstitue.py
