from pydantic import BaseModel, Field
from typing import List, Literal, Dict, Any, Optional

class ChatMessage(BaseModel):
    """Represents a single message in the chat history."""
    role: Literal["user", "assistant", "system"] = Field(
        ..., 
        description="The role of the message sender (user, assistant, or system)."
    )
    content: str = Field(
        ..., 
        description="The text content of the message."
    )

class ChatInput(BaseModel):
    """Input schema for the chat endpoint."""
    message: str = Field(
        ..., 
        description="The new message sent by the user."
    )
    history: List[ChatMessage] = Field(
        default=[], 
        description="The previous chat history between the user and the assistant."
    )
    # We could add other parameters here later, like temperature, specific model override, etc.

class ChatOutput(BaseModel):
    """Output schema for the chat endpoint."""
    response: str = Field(
        ..., 
        description="The response generated by the AI assistant."
    )
    # We could add more info later, like token usage, etc.

# Nouveaux schémas pour la génération de ressources IA

class ResourceTypeInfo(BaseModel):
    """Information sur un type de ressource générable par IA."""
    subtypes: List[str] = Field(
        ..., 
        description="Liste des sous-types disponibles pour ce type de ressource."
    )

class AIResourceTypesResponse(BaseModel):
    """Réponse listant les types de ressources IA disponibles."""
    types: Dict[str, ResourceTypeInfo] = Field(
        ...,
        description="Dictionnaire des types de ressources disponibles avec leurs sous-types."
    )

class QCMVariables(BaseModel):
    """Variables spécifiques pour générer un QCM."""
    theme: str = Field(
        ...,
        description="Thème du QCM (ex: 'La conjugaison des verbes du premier groupe')"
    )
    niveau: str = Field(
        ...,
        description="Niveau CECR (A1, A2, B1, B2, C1, C2)"
    )
    objectif_pedagogique: str = Field(
        ...,
        description="Objectif pédagogique du QCM"
    )
    nombre_questions: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Nombre de questions à générer (1-20)"
    )

class AIResourceGenerationRequest(BaseModel):
    """Requête pour générer une ressource IA."""
    type_key: str = Field(
        ...,
        description="Clé du type de ressource (ex: 'exercice')"
    )
    subtype_key: str = Field(
        ...,
        description="Clé du sous-type de ressource (ex: 'qcm')"
    )
    variables: Dict[str, Any] = Field(
        ...,
        description="Variables à injecter dans le prompt, spécifiques au type de ressource"
    )

class AIResourceGenerationResponse(BaseModel):
    """Réponse contenant le contenu généré pour une ressource IA."""
    content: Dict[str, Any] = Field(
        ...,
        description="Contenu structuré généré par l'IA"
    )
