"""add_oeuvres_table

Revision ID: 20250820_1504
Revises: d3b2d4b6c8a4
Create Date: 2025-08-20 15:04:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250820_1504'
down_revision = 'add_docling_fields_to_resources'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oeuvres',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titre', sa.String(), nullable=False),
        sa.Column('auteur', sa.JSON(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('genre', sa.String(), nullable=True),
        sa.Column('mouvement_litteraire', sa.String(), nullable=True),
        sa.Column('langue_originale', sa.String(), nullable=True),
        sa.Column('date_publication', sa.Integer(), nullable=True),
        sa.Column('extrait', sa.Boolean(), nullable=False),
        sa.Column('contenu', sa.JSON(), nullable=True),
        sa.Column('pedagogie', sa.JSON(), nullable=True),
        sa.Column('ressources', sa.JSON(), nullable=True),
        sa.Column('cree_par', sa.String(), nullable=False),
        sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oeuvres_cree_par'), 'oeuvres', ['cree_par'], unique=False)
    op.create_index(op.f('ix_oeuvres_id'), 'oeuvres', ['id'], unique=False)
    op.create_index(op.f('ix_oeuvres_titre'), 'oeuvres', ['titre'], unique=False)
    op.create_index(op.f('ix_oeuvres_type'), 'oeuvres', ['type'], unique=False)
    op.create_index(op.f('ix_oeuvres_user_id'), 'oeuvres', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oeuvres_user_id'), table_name='oeuvres')
    op.drop_index(op.f('ix_oeuvres_type'), table_name='oeuvres')
    op.drop_index(op.f('ix_oeuvres_titre'), table_name='oeuvres')
    op.drop_index(op.f('ix_oeuvres_id'), table_name='oeuvres')
    op.drop_index(op.f('ix_oeuvres_cree_par'), table_name='oeuvres')
    op.drop_table('oeuvres')
    # ### end Alembic commands ###
