"""add_html_chat_conversations_and_messages

Revision ID: 20250826_1500
Revises: d3b2d4b6c8a4
Create Date: 2025-08-26 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250826_1500'
down_revision = 'd3b2d4b6c8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create html_chat_conversations table
    op.create_table('html_chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_html_chat_conversations_id'), 'html_chat_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_html_chat_conversations_resource_id'), 'html_chat_conversations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_html_chat_conversations_user_id'), 'html_chat_conversations', ['user_id'], unique=False)
    
    # Create html_chat_messages table
    op.create_table('html_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('html_content_before', sa.Text(), nullable=True),
    sa.Column('html_content_after', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['html_chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_html_chat_messages_id'), 'html_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_html_chat_messages_conversation_id'), 'html_chat_messages', ['conversation_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop html_chat_messages table
    op.drop_index(op.f('ix_html_chat_messages_conversation_id'), table_name='html_chat_messages')
    op.drop_index(op.f('ix_html_chat_messages_id'), table_name='html_chat_messages')
    op.drop_table('html_chat_messages')
    
    # Drop html_chat_conversations table
    op.drop_index(op.f('ix_html_chat_conversations_user_id'), table_name='html_chat_conversations')
    op.drop_index(op.f('ix_html_chat_conversations_resource_id'), table_name='html_chat_conversations')
    op.drop_index(op.f('ix_html_chat_conversations_id'), table_name='html_chat_conversations')
    op.drop_table('html_chat_conversations')
    
    # ### end Alembic commands ###