"""Add study_object_oeuvre and oeuvre_resource_association tables

Revision ID: 2e492770c848
Revises: 20250820_1504
Create Date: 2025-08-20 22:08:00.486265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e492770c848'
down_revision: Union[str, None] = '20250820_1504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_object_oeuvre',
    sa.Column('study_object_id', sa.Integer(), nullable=False),
    sa.Column('oeuvre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oeuvre_id'], ['oeuvres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_object_id'], ['study_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_object_id', 'oeuvre_id')
    )
    op.create_table('oeuvre_resource_association',
    sa.Column('oeuvre_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oeuvre_id'], ['oeuvres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oeuvre_id', 'resource_id')
    )
    op.alter_column('resources', 'docling_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut Docling: pending|processing|ready|error',
               existing_nullable=True)
    op.alter_column('resources', 'docling_md_path',
               existing_type=sa.VARCHAR(),
               comment='Chemin relatif du markdown extrait (Docling)',
               existing_nullable=True)
    op.alter_column('resources', 'docling_tables_path',
               existing_type=sa.VARCHAR(),
               comment='Chemin relatif des tables extraites (Docling)',
               existing_nullable=True)
    op.alter_column('resources', 'docling_chars',
               existing_type=sa.INTEGER(),
               comment='Nombre de caractères du markdown Docling',
               existing_nullable=True)
    op.alter_column('resources', 'docling_sha256',
               existing_type=sa.VARCHAR(length=64),
               comment="Hash SHA-256 du fichier original au moment de l'extraction",
               existing_nullable=True)
    op.alter_column('resources', 'docling_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Version de Docling utilisée',
               existing_nullable=True)
    op.alter_column('resources', 'ocr_used',
               existing_type=sa.BOOLEAN(),
               comment='Extraction avec OCR utilisée',
               existing_nullable=True)
    op.alter_column('resources', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment="Horodatage de fin d'extraction",
               existing_nullable=True)
    op.alter_column('resources', 'docling_error',
               existing_type=sa.TEXT(),
               comment="Message d'erreur Docling",
               existing_nullable=True)
    op.drop_constraint('fk_sessions_fiche_resource', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'resources', ['fiche_resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('fk_sessions_fiche_resource', 'sessions', 'resources', ['fiche_resource_id'], ['id'], ondelete='SET NULL')
    op.alter_column('resources', 'docling_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Message d'erreur Docling",
               existing_nullable=True)
    op.alter_column('resources', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="Horodatage de fin d'extraction",
               existing_nullable=True)
    op.alter_column('resources', 'ocr_used',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Extraction avec OCR utilisée',
               existing_nullable=True)
    op.alter_column('resources', 'docling_version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Version de Docling utilisée',
               existing_nullable=True)
    op.alter_column('resources', 'docling_sha256',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="Hash SHA-256 du fichier original au moment de l'extraction",
               existing_nullable=True)
    op.alter_column('resources', 'docling_chars',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Nombre de caractères du markdown Docling',
               existing_nullable=True)
    op.alter_column('resources', 'docling_tables_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Chemin relatif des tables extraites (Docling)',
               existing_nullable=True)
    op.alter_column('resources', 'docling_md_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Chemin relatif du markdown extrait (Docling)',
               existing_nullable=True)
    op.alter_column('resources', 'docling_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut Docling: pending|processing|ready|error',
               existing_nullable=True)
    op.drop_table('oeuvre_resource_association')
    op.drop_table('study_object_oeuvre')
    # ### end Alembic commands ###
