"""add_order_column_to_sessions

Revision ID: 74fb8bb693af
Revises: 9aebf6672da0
Create Date: 2025-04-15 19:17:37.459559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fb8bb693af'
down_revision: Union[str, None] = '9aebf6672da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progressions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('sessions', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'order')
    op.alter_column('progressions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
