"""Add LLMInteractionLog model and table

Revision ID: 9e1a84657c54
Revises: b1e1f7e3b4e
Create Date: 2025-05-12 15:03:46.513366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e1a84657c54'
down_revision: Union[str, None] = 'b1e1f7e3b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_type', sa.String(length=100), nullable=True),
    sa.Column('input_prompt', sa.Text(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('output_content', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_token_count', sa.Integer(), nullable=True),
    sa.Column('response_token_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_interaction_logs_api_provider'), 'llm_interaction_logs', ['api_provider'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_id'), 'llm_interaction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_prompt_type'), 'llm_interaction_logs', ['prompt_type'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_user_id'), 'llm_interaction_logs', ['user_id'], unique=False)
    op.alter_column('study_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_llm_interaction_logs_user_id'), table_name='llm_interaction_logs')
    op.drop_index(op.f('ix_llm_interaction_logs_prompt_type'), table_name='llm_interaction_logs')
    op.drop_index(op.f('ix_llm_interaction_logs_id'), table_name='llm_interaction_logs')
    op.drop_index(op.f('ix_llm_interaction_logs_api_provider'), table_name='llm_interaction_logs')
    op.drop_table('llm_interaction_logs')
    # ### end Alembic commands ###
