"""change_content_type_to_text

Revision ID: a4480bszerr13
Revises: b77azery224
Create Date: 2025-04-05 10:30

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4480bszerr13'
down_revision = 'b77azery224'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'content',
               existing_type=sa.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'content',
               existing_type=sa.Text(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
