"""Initial clean snapshot

Revision ID: a76c98a1a4ff
Revises: 
Create Date: 2025-04-15 14:13:57.264264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76c98a1a4ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_sub_types_id', table_name='resource_sub_types')
    op.drop_index('ix_resource_sub_types_key', table_name='resource_sub_types')
    op.drop_table('resource_sub_types')
    op.add_column('progressions', sa.Column('order', sa.Integer(), nullable=True))
    op.alter_column('resource_subtypes', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resource_subtypes', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_resource_subtypes_key', table_name='resource_subtypes')
    op.create_index(op.f('ix_resource_subtypes_key'), 'resource_subtypes', ['key'], unique=False)
    op.alter_column('resource_types', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resource_types', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resources', 'sub_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'sub_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resource_types', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resource_types', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_resource_subtypes_key'), table_name='resource_subtypes')
    op.create_index('ix_resource_subtypes_key', 'resource_subtypes', ['key'], unique=False)
    op.alter_column('resource_subtypes', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resource_subtypes', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # Ajout correct de la colonne 'order' même si des lignes existent déjà
    op.add_column('progressions', sa.Column('order', sa.Integer(), nullable=True))
    op.execute('UPDATE progressions SET "order" = 0 WHERE "order" IS NULL')
    op.alter_column('progressions', 'order', nullable=False)

    op.create_table('resource_sub_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['resource_types.id'], name='resource_sub_types_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resource_sub_types_pkey')
    )
    op.create_index('ix_resource_sub_types_key', 'resource_sub_types', ['key'], unique=False)
    op.create_index('ix_resource_sub_types_id', 'resource_sub_types', ['id'], unique=False)
    # ### end Alembic commands ###
