"""add user_id to study_objects

Revision ID: c55e4e32868a
Revises: 9e1a84657c54
Create Date: 2025-06-12 14:11:49.236577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55e4e32868a'
down_revision: Union[str, None] = '9e1a84657c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_objects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_study_objects_user_id'), 'study_objects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'study_objects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_objects', type_='foreignkey')
    op.drop_index(op.f('ix_study_objects_user_id'), table_name='study_objects')
    op.drop_column('study_objects', 'user_id')
    # ### end Alembic commands ###
